const ALERT = "ALERT";
const REFETCH_CHATS = "REFETCH_CHATS";
const REFETCH_REQUESTS = "REFETCH_REQUESTS";
const REFETCH_MEMBERS = "REFETCH_MEMBERS";
const REFETCH_MESSAGES = "REFETCH_MESSAGES";

const CHAT_JOINED = "CHAT_JOINED";
const CHAT_LEFT = "CHAT_LEFT";
const ONLINE_USERS = "ONLINE_USERS";

const NEW_ATTACHMENT = "NEW_ATTACHMENT";
const NEW_MESSAGE_ALERT = "NEW_MESSAGE_ALERT";

const NEW_REQUEST = "NEW_REQUEST";

const NEW_MESSAGE = "NEW_MESSAGE";

const START_TYPING = "START_TYPING";
const STOP_TYPING = "STOP_TYPING";

module.exports = {ALERT, REFETCH_CHATS, NEW_ATTACHMENT, NEW_MESSAGE_ALERT, NEW_REQUEST, NEW_MESSAGE, START_TYPING, STOP_TYPING, REFETCH_REQUESTS, REFETCH_MEMBERS, REFETCH_MESSAGES, CHAT_JOINED, CHAT_LEFT, ONLINE_USERS};
